server:
  port: 51586
  servlet:
    context-path: /app

utils:
  cart:
    prefix: SPRING_WEB_

spring:
  application:
    name: front-service


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      fetchRegistry: false


